services:
  booking_backend_service:
    container_name: 'booking_backend'
    image: booking-api-image
    networks:
      - booking_network
    environment:
      - MODE=PROD

  booking_celery_worker_service:
    container_name: 'booking_celery_worker'
    image: booking-api-image
    networks:
      - booking_network
    command:
      ["celery", "--app=src.core.tasks.celery_app:celery_instance", "worker", "-l", "INFO"]

  booking_celery_beat_service:
    container_name: 'booking_celery_beat'
    image: booking-api-image
    networks:
      - booking_network
    command:
      ["celery", "--app=src.core.tasks.celery_app:celery_instance", "beat", "-l", "INFO" ]

networks:
  booking_network:
    external: True
